empt: emp.o empt.o qs.o ins.o
	gcc -g emp.o empt.o qs.o ins.o -o empt

empt.o: empt.c emp.h
	gcc -g -c empt.c -o empt.o

emp.o: emp.c emp.h
	gcc -g -c emp.c -o emp.o

qs.o: qs.c qs.h
	gcc -g -c qs.c -o qs.o

ins.o: ins.c ins.h
	gcc -g -c ins.c -o ins.o




